runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cron/.*
  script: app.app
  login: admin
  secure: always
- url: /.*
  script: app.app
  secure: always

libraries:
- name: flask
  version: "0.12"
